backend:
  name: github
  repo: damienvdw/codex-koryll # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "adversaires" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Adversaires" # Used in the UI, ie.: "New Post"
    folder: "source/_posts/adversaires" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Categories", name: "categories", widget: "string", default: "Adversaires"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "factions"
    label: "Factions"
    folder: "source/_posts/factions"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Categories", name: "categories", widget: "string", default: "Factions"}
      - {label: "Body", name: "body", widget: "markdown"}      
  - name: "lieux"
    label: "Lieux"
    folder: "source/_posts/lieux"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Categories", name: "categories", widget: "string", default: "Lieux"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "npc"
    label: "NPC"
    folder: "source/_posts/npc"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Categories", name: "categories", widget: "string", default: "NPC"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pc"
    label: "PC"
    folder: "source/_posts/pc"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Categories", name: "categories", widget: "string", default: "PC"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "plots"
    label: "Plots"
    folder: "source/_posts/plots"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Categories", name: "categories", widget: "string", default: "Plots"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "plots_saison1"
    label: "Plots / Saison 1"
    folder: "source/_posts/plots/Saison_01"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Categories", name: "categories", widget: "string", default: "Plots Saison01"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "regles"
    label: "Regles"
    folder: "source/_posts/regles"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Categories", name: "categories", widget: "string", default: "Règles"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "religion"
    label: "Religion"
    folder: "source/_posts/religion"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Categories", name: "categories", widget: "string", default: "Religion"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "univers"
    label: "Univers"
    folder: "source/_posts/univers"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Categories", name: "categories", widget: "string", default: "Univers"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "zones"
    label: "Zones"
    folder: "source/_posts/zones"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Categories", name: "categories", widget: "string", default: "Zones"}    
      - {label: "Body", name: "body", widget: "markdown"}